#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    sum1 = 0
    sumSq = 0
    for i in range(1,n+1):
        sum1 += i
        sumSq += i*i
    sqSum = sum1*sum1
    print(abs(sumSq - sqSum))
