#!/bin/python3

import math
import os
import random
import re
import sys
import string

#
# Complete the 'minimumNumber' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. STRING password
#

def minimumNumber(n, password):
    digit = "0123456789"
    lower = string.ascii_lowercase
    upper = string.ascii_uppercase
    special = "!@#$%^&*()-+"
        
    
    req = 4
    s,l,u,d = 0,0,0,0
    
    for ch in password:
        if ch in special:
            s = 1
        if ch in lower:
            l = 1
        if ch in upper:
            u = 1
        if ch in digit:
            d = 1
            
    slud = s+l+u+d
    req -= slud
    shortfall = 6 - n
    if shortfall < 0:
        shortfall = 0
    if req > shortfall:
        shortfall = req
    
    return shortfall
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
